name: Standard CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  security-events: write
  actions: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout-code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

  # ==========================================
  # PARALLEL STAGE 1: FAST CHECKS
  # ==========================================
  gitleaks-scan:
    needs: checkout-code
    uses: nlttin/singpost-cicd-components/.github/workflows/reusable-workflow-gitleaks.yml@main
    with:
      scan_mode: full
      fail-on-detection: false
    secrets: inherit

  checkov-scan:
    needs: checkout-code
    uses: nlttin/singpost-cicd-components/.github/workflows/reusable-workflow-checkov.yml@feature/checkov
    with:
      config-path: ./.github/config/checkov.yml
    secrets: inherit

  # ==========================================
  # STAGE 2: SECURITY SCANS
  # ==========================================
  security-scans:
    needs: [gitleaks-scan, checkov-scan]
    runs-on: ubuntu-latest
    steps:
  #    - run: echo "Mocking CodeQL & SonarQube"
      - run: echo "Mocking Checkov"

  # ==========================================
  # STAGE 3: DEPLOYMENTS
  # ==========================================
  deploy-dev:
    needs: security-scans
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo "Mocking Terraform DEV"
      - run: echo "Mocking Apigee DEV"
      - run: echo "Mocking Cloud Deploy GKE DEV"

  deploy-prod:
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Mocking Terraform PROD"
      - run: echo "Mocking Apigee PROD"
      - run: echo "Mocking Cloud Deploy GKE PROD"

  # ==========================================
  # STAGE 4: NOTIFY
  # ==========================================
  notify:
    if: always()
    needs: [deploy-dev, deploy-prod]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mocking GChat Webhook"